Method 1: Manual implentation in mean

In [2]:
num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
sum = 0

for i in num:
    sum = sum + i

n = len(num)  
mean_val = sum / n  

print(mean_val)

5.5

Method 2: Numpy Method

In [3]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.mean())

5.5

Method 3: using Statistics

In [4]:
import statistics as st
data=[1,2,3,4,5,6,7,8,9,10]
mean_val=st.mean(data)
print(mean_val)

5.5

In [5]:
import numpy as np
import seaborn as sns

In [6]:
iris=sns.load_dataset('iris')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [7]:
print(np.mean(iris['sepal_length']))

5.843333333333334

Method 1: Manually calculated Median

In [8]:
data = [40, 50, 60, 70, 100,120]
data.sort()
n=len(data)
mid=n//2
if n%2==1:
    median=data[mid]
else:
    median=(data[mid-1] + data[mid])/2

print(median)

65.0

Method 2: using Numpy

In [9]:
import numpy as np 
data = [40, 50, 60, 70, 100,120]
num=np.median(data)
print(num)

65.0

Method 3: using statistics

In [10]:
import statistics as stats
data = [40, 50, 60, 70, 100,120]
num=stats.median(data)
print(num)

65.0

Method 1 : Manually Mode

In [15]:
data=[2,2,2,2,2,2,3,3,3,3,3,5,5,5,5,6,6,6,6,7]
freq={}
for i in data:
    if i in freq:
        freq[i]+=1
    else:
        freq[i]=1
max_freq=max(freq.values())

for key,value in freq.items():
    if value==max_freq:
        print("Mode is",key)
        break

Mode is 2

**method 2; mode using scipy**

In [19]:
from scipy import stats
data=[2,2,2,2,2,2,3,3,3,3,3,5,5,5,5,6,6,6,6,7]
mode=stats.mode(data)
print(mode)

ModeResult(mode=2, count=6)

**Method 3 mode using statistics**

In [20]:
import statistics as stats
data=[2,2,2,2,2,2,3,3,3,3,3,5,5,5,5,6,6,6,6,7]
mode=stats.mode(data)
print(mode)

2